---
galaxy_info:
  role_name: wordpress
  namespace: mikroways
  author: FranciscoPerez
  description: "Instala y configura WordPress con Apache y PHP, compatible con Ubuntu/Debian y Rocky/RedHat."
  company: "Mikroways"
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
    - name: Debian
      versions:
        - 11
        - 12
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - wordpress
    - apache
    - php
    - web
    - cms
    - molecule

allow_duplicates: false
