php_packages:
  - php
  - php-curl
  - php-dom
  - php-exif
  - php-fileinfo
  - php-hash
  - php-igbinary
  - php-imagick
  - php-intl
  - php-mbstring
  - php-openssl
  - php-pcre
  - php-xml
  - php-zip

apache_packages:
  - httpd
  - php