---
- name: Instalar Wordpress con MySQL
  hosts: all
  gather_facts: true
  # become: true
  vars:
    wordpress_db_name: wp_db
    wordpress_db_host: localhost
    wordpress_db_user: wp-user
    wordpress_db_password: wp-pass
  pre_tasks:
    - name: Obtener info de sistema para debug
      ansible.builtin.debug:
        msg: |
          os_family: {{ ansible_os_family }}
          distribution: {{ ansible_distribution }}
          major_version: {{ ansible_distribution_major_version }}
  roles:
    - role: wordpress
      vars:
        wordpress_apache_server_name: localhost
        wordpress_dir: "/var/www/{{ wordpress_apache_server_name }}"
        wordpress_apache_dir: "/var/www/{{ wordpress_apache_server_name }}/wordpress"
    - role: geerlingguy.mysql
      vars:
        mysql_daemon: mysqld
        mysql_service_name: mysqld
        mysql_server_id: "1"
        mysql_max_binlog_size: "100M"
        mysql_binlog_format: "ROW"
        mysql_expire_logs_days: "10"
        mysql_replication_role: ''
        mysql_replication_master: "localhost"
        mysql_replication_user: {}
        mysql_databases:
          - name: "{{ wordpress_db_name }}"
        mysql_users:
          - name: "{{ wordpress_db_user }}"
            host: "localhost"
            password: "{{ wordpress_db_password }}"
            priv: "{{ wordpress_db_name }}.*:ALL"
