driver:
  name: docker

platforms:
  - name: ubuntu
    image: ubuntu:20.04
    privileged: true
    ports:
      - "8888:80"

  - name: rockylinux
    image: geerlingguy/docker-rockylinux9-ansible
    privileged: true
    ports:
      - "8889:80"

provisioner:
  name: ansible
  options:
    become: false
