name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: [default]
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible roles
        run: ansible-galaxy install -r requirements.yml
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml -p ./collections
      - name: List installed collections
        run: ansible-galaxy collection list
      - name: Run Molecule tests
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
          molecule_working_dir: roles/wordpress
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_COLLECTIONS_PATHS: ./collections
