name: Molecule

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test role with Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker ansible molecule molecule-plugins[docker] 

      - name: Install Ansible roles
        run: ansible-galaxy install -r requirements.yml
      - name: Install Ansible collections
      
        run: ansible-galaxy collection install -r requirements.yml
      - name: List installed collections
        run: ansible-galaxy collection list

      - name: Run Molecule test
        run: |
          cd roles/wordpress
          ls
          molecule test