name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List molecule folder
        run: ls -lR roles/wordpress/molecule/default

      - name: Run Molecule tests
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: roles/wordpress/molecule/default
        env:
          ANSIBLE_FORCE_COLOR: '1'

